#############################################################################
# Makefile for building: AspeQt
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  aspeqt.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile aspeqt.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DVERSION=\"r5.13L\" -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -D_REENTRANT -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -D_REENTRANT -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5/QtZlib -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtSerialPort -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = AspeQt1.0.0
DISTDIR = /home/paul/qtProjects/AspeQt-2020/.tmp/AspeQt1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lz /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5SerialPort.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		sioworker.cpp \
		optionsdialog.cpp \
		aboutdialog.cpp \
		diskimage.cpp \
		diskimagepro.cpp \
		folderimage.cpp \
		miscdevices.cpp \
		createimagedialog.cpp \
		diskeditdialog.cpp \
		autoboot.cpp \
		autobootdialog.cpp \
		atarifilesystem.cpp \
		miscutils.cpp \
		textprinterwindow.cpp \
		cassettedialog.cpp \
		docdisplaywindow.cpp \
		bootoptionsdialog.cpp \
		network.cpp \
		logdisplaydialog.cpp \
		drivewidget.cpp \
		pclink.cpp \
		infowidget.cpp \
		aspeqtsettings.cpp \
		serialport-unix.cpp qrc_icons.cpp \
		qrc_i18n.cpp \
		qrc_documentation.cpp \
		qrc_atarifiles.cpp \
		moc_mainwindow.cpp \
		moc_serialport.cpp \
		moc_sioworker.cpp \
		moc_optionsdialog.cpp \
		moc_aboutdialog.cpp \
		moc_diskimage.cpp \
		moc_diskimagepro.cpp \
		moc_folderimage.cpp \
		moc_miscdevices.cpp \
		moc_createimagedialog.cpp \
		moc_diskeditdialog.cpp \
		moc_autoboot.cpp \
		moc_autobootdialog.cpp \
		moc_atarifilesystem.cpp \
		moc_miscutils.cpp \
		moc_textprinterwindow.cpp \
		moc_cassettedialog.cpp \
		moc_docdisplaywindow.cpp \
		moc_bootoptionsdialog.cpp \
		moc_network.cpp \
		moc_logdisplaydialog.cpp \
		moc_drivewidget.cpp \
		moc_pclink.cpp \
		moc_infowidget.cpp \
		moc_serialport-unix.cpp
OBJECTS       = main.o \
		mainwindow.o \
		sioworker.o \
		optionsdialog.o \
		aboutdialog.o \
		diskimage.o \
		diskimagepro.o \
		folderimage.o \
		miscdevices.o \
		createimagedialog.o \
		diskeditdialog.o \
		autoboot.o \
		autobootdialog.o \
		atarifilesystem.o \
		miscutils.o \
		textprinterwindow.o \
		cassettedialog.o \
		docdisplaywindow.o \
		bootoptionsdialog.o \
		network.o \
		logdisplaydialog.o \
		drivewidget.o \
		pclink.o \
		infowidget.o \
		aspeqtsettings.o \
		serialport-unix.o \
		qrc_icons.o \
		qrc_i18n.o \
		qrc_documentation.o \
		qrc_atarifiles.o \
		moc_mainwindow.o \
		moc_serialport.o \
		moc_sioworker.o \
		moc_optionsdialog.o \
		moc_aboutdialog.o \
		moc_diskimage.o \
		moc_diskimagepro.o \
		moc_folderimage.o \
		moc_miscdevices.o \
		moc_createimagedialog.o \
		moc_diskeditdialog.o \
		moc_autoboot.o \
		moc_autobootdialog.o \
		moc_atarifilesystem.o \
		moc_miscutils.o \
		moc_textprinterwindow.o \
		moc_cassettedialog.o \
		moc_docdisplaywindow.o \
		moc_bootoptionsdialog.o \
		moc_network.o \
		moc_logdisplaydialog.o \
		moc_drivewidget.o \
		moc_pclink.o \
		moc_infowidget.o \
		moc_serialport-unix.o
DIST          = atari/autoboot/autoboot.bin \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		aspeqt.pro mainwindow.h \
		serialport.h \
		sioworker.h \
		optionsdialog.h \
		aboutdialog.h \
		diskimage.h \
		diskimagepro.h \
		folderimage.h \
		miscdevices.h \
		createimagedialog.h \
		diskeditdialog.h \
		autoboot.h \
		autobootdialog.h \
		atarifilesystem.h \
		miscutils.h \
		textprinterwindow.h \
		cassettedialog.h \
		docdisplaywindow.h \
		bootoptionsdialog.h \
		network.h \
		logdisplaydialog.h \
		drivewidget.h \
		pclink.h \
		infowidget.h \
		aspeqtsettings.h \
		serialport-unix.h main.cpp \
		mainwindow.cpp \
		sioworker.cpp \
		optionsdialog.cpp \
		aboutdialog.cpp \
		diskimage.cpp \
		diskimagepro.cpp \
		folderimage.cpp \
		miscdevices.cpp \
		createimagedialog.cpp \
		diskeditdialog.cpp \
		autoboot.cpp \
		autobootdialog.cpp \
		atarifilesystem.cpp \
		miscutils.cpp \
		textprinterwindow.cpp \
		cassettedialog.cpp \
		docdisplaywindow.cpp \
		bootoptionsdialog.cpp \
		network.cpp \
		logdisplaydialog.cpp \
		drivewidget.cpp \
		pclink.cpp \
		infowidget.cpp \
		aspeqtsettings.cpp \
		serialport-unix.cpp
QMAKE_TARGET  = AspeQt
DESTDIR       = 
TARGET        = AspeQt


first: all
####### Build rules

AspeQt: ui_mainwindow.h ui_optionsdialog.h ui_aboutdialog.h ui_createimagedialog.h ui_diskeditdialog.h ui_autobootdialog.h ui_textprinterwindow.h ui_cassettedialog.h ui_docdisplaywindow.h ui_bootoptionsdialog.h ui_logdisplaydialog.h ui_drivewidget.h ui_infowidget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: aspeqt.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		aspeqt.pro \
		icons.qrc \
		i18n.qrc \
		documentation.qrc \
		atarifiles.qrc
	$(QMAKE) -o Makefile aspeqt.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
aspeqt.pro:
icons.qrc:
i18n.qrc:
documentation.qrc:
atarifiles.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile aspeqt.pro

qmake_all: FORCE


all: Makefile AspeQt

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents icons.qrc i18n.qrc documentation.qrc atarifiles.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h serialport.h sioworker.h optionsdialog.h aboutdialog.h diskimage.h diskimagepro.h folderimage.h miscdevices.h createimagedialog.h diskeditdialog.h autoboot.h autobootdialog.h atarifilesystem.h miscutils.h textprinterwindow.h cassettedialog.h docdisplaywindow.h bootoptionsdialog.h network.h logdisplaydialog.h drivewidget.h pclink.h infowidget.h aspeqtsettings.h serialport-unix.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp sioworker.cpp optionsdialog.cpp aboutdialog.cpp diskimage.cpp diskimagepro.cpp folderimage.cpp miscdevices.cpp createimagedialog.cpp diskeditdialog.cpp autoboot.cpp autobootdialog.cpp atarifilesystem.cpp miscutils.cpp textprinterwindow.cpp cassettedialog.cpp docdisplaywindow.cpp bootoptionsdialog.cpp network.cpp logdisplaydialog.cpp drivewidget.cpp pclink.cpp infowidget.cpp aspeqtsettings.cpp serialport-unix.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui optionsdialog.ui aboutdialog.ui createimagedialog.ui diskeditdialog.ui autobootdialog.ui textprinterwindow.ui cassettedialog.ui docdisplaywindow.ui bootoptionsdialog.ui logdisplaydialog.ui drivewidget.ui infowidget.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_icons.cpp qrc_i18n.cpp qrc_documentation.cpp qrc_atarifiles.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp qrc_i18n.cpp qrc_documentation.cpp qrc_atarifiles.cpp
qrc_icons.cpp: icons.qrc \
		/usr/lib/qt5/bin/rcc \
		Atari.ico \
		silk-icons/icons/drive_disk.png \
		silk-icons/icons/folder.png \
		silk-icons/icons/font.png \
		silk-icons/icons/drive.png \
		silk-icons/icons/shape_square.png \
		silk-icons/icons/disconnect.png \
		silk-icons/icons/arrow_up.png \
		silk-icons/icons/delete.png \
		silk-icons/icons/drive_go.png \
		silk-icons/icons/drive_add.png \
		silk-icons/icons/page_white.png \
		silk-icons/icons/monitor.png \
		silk-icons/icons/printer.png \
		silk-icons/icons/lock.png \
		silk-icons/icons/add.png \
		silk-icons/icons/font_go.png \
		silk-icons/icons/page_white_text.png \
		silk-icons/icons/disk.png \
		silk-icons/icons/text_align_left.png \
		silk-icons/icons/lock_open.png \
		silk-icons/icons/page_white_go.png \
		silk-icons/icons/application.png \
		silk-icons/icons/drive_delete.png \
		silk-icons/icons/arrow_right.png \
		silk-icons/icons/connect.png \
		silk-icons/icons/drive_rename.png \
		silk-icons/icons/cut_red.png \
		silk-icons/icons/monitor_go.png \
		silk-icons/icons/page_white_c.png \
		silk-icons/icons/control_eject.png \
		silk-icons/icons/arrow_undo.png \
		silk-icons/icons/folder_edit.png \
		silk-icons/icons/printer_delete.png \
		other-icons/MiniCooper\ 22.ico \
		other-icons/fuji.png \
		other-icons/move.png \
		other-icons/run.ico \
		other-icons/fade.png \
		oxygen-icons/16x16/actions/document_save_all.png \
		oxygen-icons/16x16/actions/network_connect.png \
		oxygen-icons/16x16/actions/network.png \
		oxygen-icons/16x16/actions/flag_red.png \
		oxygen-icons/16x16/actions/flag_green.png \
		oxygen-icons/16x16/actions/view_right_close.png \
		oxygen-icons/16x16/actions/format_font_size_more.png \
		oxygen-icons/16x16/actions/view_left_close.png \
		oxygen-icons/16x16/actions/exit.png \
		oxygen-icons/16x16/actions/help_about.png \
		oxygen-icons/16x16/actions/network_disconnect.png \
		oxygen-icons/16x16/actions/help_contents.png \
		oxygen-icons/16x16/devices/3floppy_mount.png \
		oxygen-icons/16x16/devices/media_tape.png \
		oxygen-icons/16x16/devices/printer1.png \
		oxygen-icons/16x16/devices/media_floppy.png \
		oxygen-icons/16x16/devices/3floppy_unmount.png \
		main-icon/icon.jpeg \
		main-icon/AspeQt.ico \
		main-icon/main16.png
	/usr/lib/qt5/bin/rcc -name icons icons.qrc -o qrc_icons.cpp

qrc_i18n.cpp: i18n.qrc \
		/usr/lib/qt5/bin/rcc \
		i18n/qt_sk.qm \
		i18n/qt_de.qm \
		i18n/respeqt_ru.qm \
		i18n/qt_pl.qm \
		i18n/respeqt_es.qm \
		i18n/qt_ru.qm \
		i18n/respeqt_tr.qm \
		i18n/qt_es.qm \
		i18n/qt_tr.qm \
		i18n/respeqt_sk.qm \
		i18n/respeqt_de.qm \
		i18n/respeqt_pl.qm
	/usr/lib/qt5/bin/rcc -name i18n i18n.qrc -o qrc_i18n.cpp

qrc_documentation.cpp: documentation.qrc \
		/usr/lib/qt5/bin/rcc \
		about.html \
		about_spanish.html \
		history.txt \
		license.txt \
		AspeQt\ User\ Manual-English.html
	/usr/lib/qt5/bin/rcc -name documentation documentation.qrc -o qrc_documentation.cpp

qrc_atarifiles.cpp: atarifiles.qrc \
		/usr/lib/qt5/bin/rcc \
		atari/autoboot/autoboot.bin \
		atari/autoboot/autoboot-hispeed.bin
	/usr/lib/qt5/bin/rcc -name atarifiles atarifiles.qrc -o qrc_atarifiles.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_serialport.cpp moc_sioworker.cpp moc_optionsdialog.cpp moc_aboutdialog.cpp moc_diskimage.cpp moc_diskimagepro.cpp moc_folderimage.cpp moc_miscdevices.cpp moc_createimagedialog.cpp moc_diskeditdialog.cpp moc_autoboot.cpp moc_autobootdialog.cpp moc_atarifilesystem.cpp moc_miscutils.cpp moc_textprinterwindow.cpp moc_cassettedialog.cpp moc_docdisplaywindow.cpp moc_bootoptionsdialog.cpp moc_network.cpp moc_logdisplaydialog.cpp moc_drivewidget.cpp moc_pclink.cpp moc_infowidget.cpp moc_serialport-unix.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_serialport.cpp moc_sioworker.cpp moc_optionsdialog.cpp moc_aboutdialog.cpp moc_diskimage.cpp moc_diskimagepro.cpp moc_folderimage.cpp moc_miscdevices.cpp moc_createimagedialog.cpp moc_diskeditdialog.cpp moc_autoboot.cpp moc_autobootdialog.cpp moc_atarifilesystem.cpp moc_miscutils.cpp moc_textprinterwindow.cpp moc_cassettedialog.cpp moc_docdisplaywindow.cpp moc_bootoptionsdialog.cpp moc_network.cpp moc_logdisplaydialog.cpp moc_drivewidget.cpp moc_pclink.cpp moc_infowidget.cpp moc_serialport-unix.cpp
moc_mainwindow.cpp: mainwindow.h \
		optionsdialog.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aboutdialog.h \
		createimagedialog.h \
		diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		miscutils.h \
		textprinterwindow.h \
		docdisplaywindow.h \
		network.h \
		drivewidget.h \
		infowidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paul/qtProjects/AspeQt-2020/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paul/qtProjects/AspeQt-2020 -I/usr/include/x86_64-linux-gnu/qt5/QtZlib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_serialport.cpp: serialport.h \
		serialport-win32.h \
		serialport.h \
		serialport-unix.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paul/qtProjects/AspeQt-2020/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paul/qtProjects/AspeQt-2020 -I/usr/include/x86_64-linux-gnu/qt5/QtZlib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include serialport.h -o moc_serialport.cpp

moc_sioworker.cpp: sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paul/qtProjects/AspeQt-2020/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paul/qtProjects/AspeQt-2020 -I/usr/include/x86_64-linux-gnu/qt5/QtZlib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include sioworker.h -o moc_sioworker.cpp

moc_optionsdialog.cpp: optionsdialog.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paul/qtProjects/AspeQt-2020/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paul/qtProjects/AspeQt-2020 -I/usr/include/x86_64-linux-gnu/qt5/QtZlib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include optionsdialog.h -o moc_optionsdialog.cpp

moc_aboutdialog.cpp: aboutdialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paul/qtProjects/AspeQt-2020/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paul/qtProjects/AspeQt-2020 -I/usr/include/x86_64-linux-gnu/qt5/QtZlib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include aboutdialog.h -o moc_aboutdialog.cpp

moc_diskimage.cpp: diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paul/qtProjects/AspeQt-2020/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paul/qtProjects/AspeQt-2020 -I/usr/include/x86_64-linux-gnu/qt5/QtZlib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include diskimage.h -o moc_diskimage.cpp

moc_diskimagepro.cpp: diskimagepro.h \
		diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paul/qtProjects/AspeQt-2020/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paul/qtProjects/AspeQt-2020 -I/usr/include/x86_64-linux-gnu/qt5/QtZlib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include diskimagepro.h -o moc_diskimagepro.cpp

moc_folderimage.cpp: folderimage.h \
		diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paul/qtProjects/AspeQt-2020/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paul/qtProjects/AspeQt-2020 -I/usr/include/x86_64-linux-gnu/qt5/QtZlib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include folderimage.h -o moc_folderimage.cpp

moc_miscdevices.cpp: miscdevices.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paul/qtProjects/AspeQt-2020/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paul/qtProjects/AspeQt-2020 -I/usr/include/x86_64-linux-gnu/qt5/QtZlib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include miscdevices.h -o moc_miscdevices.cpp

moc_createimagedialog.cpp: createimagedialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paul/qtProjects/AspeQt-2020/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paul/qtProjects/AspeQt-2020 -I/usr/include/x86_64-linux-gnu/qt5/QtZlib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include createimagedialog.h -o moc_createimagedialog.cpp

moc_diskeditdialog.cpp: diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paul/qtProjects/AspeQt-2020/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paul/qtProjects/AspeQt-2020 -I/usr/include/x86_64-linux-gnu/qt5/QtZlib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include diskeditdialog.h -o moc_diskeditdialog.cpp

moc_autoboot.cpp: autoboot.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paul/qtProjects/AspeQt-2020/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paul/qtProjects/AspeQt-2020 -I/usr/include/x86_64-linux-gnu/qt5/QtZlib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include autoboot.h -o moc_autoboot.cpp

moc_autobootdialog.cpp: autobootdialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paul/qtProjects/AspeQt-2020/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paul/qtProjects/AspeQt-2020 -I/usr/include/x86_64-linux-gnu/qt5/QtZlib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include autobootdialog.h -o moc_autobootdialog.cpp

moc_atarifilesystem.cpp: atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paul/qtProjects/AspeQt-2020/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paul/qtProjects/AspeQt-2020 -I/usr/include/x86_64-linux-gnu/qt5/QtZlib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include atarifilesystem.h -o moc_atarifilesystem.cpp

moc_miscutils.cpp: miscutils.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paul/qtProjects/AspeQt-2020/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paul/qtProjects/AspeQt-2020 -I/usr/include/x86_64-linux-gnu/qt5/QtZlib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include miscutils.h -o moc_miscutils.cpp

moc_textprinterwindow.cpp: textprinterwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paul/qtProjects/AspeQt-2020/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paul/qtProjects/AspeQt-2020 -I/usr/include/x86_64-linux-gnu/qt5/QtZlib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include textprinterwindow.h -o moc_textprinterwindow.cpp

moc_cassettedialog.cpp: cassettedialog.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paul/qtProjects/AspeQt-2020/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paul/qtProjects/AspeQt-2020 -I/usr/include/x86_64-linux-gnu/qt5/QtZlib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include cassettedialog.h -o moc_cassettedialog.cpp

moc_docdisplaywindow.cpp: docdisplaywindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paul/qtProjects/AspeQt-2020/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paul/qtProjects/AspeQt-2020 -I/usr/include/x86_64-linux-gnu/qt5/QtZlib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include docdisplaywindow.h -o moc_docdisplaywindow.cpp

moc_bootoptionsdialog.cpp: bootoptionsdialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paul/qtProjects/AspeQt-2020/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paul/qtProjects/AspeQt-2020 -I/usr/include/x86_64-linux-gnu/qt5/QtZlib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include bootoptionsdialog.h -o moc_bootoptionsdialog.cpp

moc_network.cpp: network.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paul/qtProjects/AspeQt-2020/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paul/qtProjects/AspeQt-2020 -I/usr/include/x86_64-linux-gnu/qt5/QtZlib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include network.h -o moc_network.cpp

moc_logdisplaydialog.cpp: logdisplaydialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paul/qtProjects/AspeQt-2020/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paul/qtProjects/AspeQt-2020 -I/usr/include/x86_64-linux-gnu/qt5/QtZlib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include logdisplaydialog.h -o moc_logdisplaydialog.cpp

moc_drivewidget.cpp: drivewidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paul/qtProjects/AspeQt-2020/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paul/qtProjects/AspeQt-2020 -I/usr/include/x86_64-linux-gnu/qt5/QtZlib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include drivewidget.h -o moc_drivewidget.cpp

moc_pclink.cpp: pclink.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paul/qtProjects/AspeQt-2020/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paul/qtProjects/AspeQt-2020 -I/usr/include/x86_64-linux-gnu/qt5/QtZlib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include pclink.h -o moc_pclink.cpp

moc_infowidget.cpp: infowidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paul/qtProjects/AspeQt-2020/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paul/qtProjects/AspeQt-2020 -I/usr/include/x86_64-linux-gnu/qt5/QtZlib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include infowidget.h -o moc_infowidget.cpp

moc_serialport-unix.cpp: serialport-unix.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/paul/qtProjects/AspeQt-2020/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/paul/qtProjects/AspeQt-2020 -I/usr/include/x86_64-linux-gnu/qt5/QtZlib -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include serialport-unix.h -o moc_serialport-unix.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_optionsdialog.h ui_aboutdialog.h ui_createimagedialog.h ui_diskeditdialog.h ui_autobootdialog.h ui_textprinterwindow.h ui_cassettedialog.h ui_docdisplaywindow.h ui_bootoptionsdialog.h ui_logdisplaydialog.h ui_drivewidget.h ui_infowidget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_optionsdialog.h ui_aboutdialog.h ui_createimagedialog.h ui_diskeditdialog.h ui_autobootdialog.h ui_textprinterwindow.h ui_cassettedialog.h ui_docdisplaywindow.h ui_bootoptionsdialog.h ui_logdisplaydialog.h ui_drivewidget.h ui_infowidget.h
ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_optionsdialog.h: optionsdialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic optionsdialog.ui -o ui_optionsdialog.h

ui_aboutdialog.h: aboutdialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic aboutdialog.ui -o ui_aboutdialog.h

ui_createimagedialog.h: createimagedialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic createimagedialog.ui -o ui_createimagedialog.h

ui_diskeditdialog.h: diskeditdialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic diskeditdialog.ui -o ui_diskeditdialog.h

ui_autobootdialog.h: autobootdialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic autobootdialog.ui -o ui_autobootdialog.h

ui_textprinterwindow.h: textprinterwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic textprinterwindow.ui -o ui_textprinterwindow.h

ui_cassettedialog.h: cassettedialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic cassettedialog.ui -o ui_cassettedialog.h

ui_docdisplaywindow.h: docdisplaywindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic docdisplaywindow.ui -o ui_docdisplaywindow.h

ui_bootoptionsdialog.h: bootoptionsdialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic bootoptionsdialog.ui -o ui_bootoptionsdialog.h

ui_logdisplaydialog.h: logdisplaydialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic logdisplaydialog.ui -o ui_logdisplaydialog.h

ui_drivewidget.h: drivewidget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic drivewidget.ui -o ui_drivewidget.h

ui_infowidget.h: infowidget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic infowidget.ui -o ui_infowidget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		optionsdialog.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aboutdialog.h \
		createimagedialog.h \
		diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		miscutils.h \
		textprinterwindow.h \
		docdisplaywindow.h \
		network.h \
		drivewidget.h \
		infowidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		optionsdialog.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aboutdialog.h \
		createimagedialog.h \
		diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		miscutils.h \
		textprinterwindow.h \
		docdisplaywindow.h \
		network.h \
		drivewidget.h \
		infowidget.h \
		ui_mainwindow.h \
		diskimagepro.h \
		folderimage.h \
		pclink.h \
		miscdevices.h \
		aspeqtsettings.h \
		autobootdialog.h \
		autoboot.h \
		cassettedialog.h \
		bootoptionsdialog.h \
		logdisplaydialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

sioworker.o: sioworker.cpp sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aspeqtsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sioworker.o sioworker.cpp

optionsdialog.o: optionsdialog.cpp optionsdialog.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		ui_optionsdialog.h \
		aspeqtsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optionsdialog.o optionsdialog.cpp

aboutdialog.o: aboutdialog.cpp aboutdialog.h \
		ui_aboutdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aboutdialog.o aboutdialog.cpp

diskimage.o: diskimage.cpp diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		aspeqtsettings.h \
		atarifilesystem.h \
		diskeditdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diskimage.o diskimage.cpp

diskimagepro.o: diskimagepro.cpp diskimagepro.h \
		diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diskimagepro.o diskimagepro.cpp

folderimage.o: folderimage.cpp folderimage.h \
		diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		aspeqtsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o folderimage.o folderimage.cpp

miscdevices.o: miscdevices.cpp miscdevices.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aspeqtsettings.h \
		mainwindow.h \
		optionsdialog.h \
		aboutdialog.h \
		createimagedialog.h \
		diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		miscutils.h \
		textprinterwindow.h \
		docdisplaywindow.h \
		network.h \
		drivewidget.h \
		infowidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o miscdevices.o miscdevices.cpp

createimagedialog.o: createimagedialog.cpp createimagedialog.h \
		ui_createimagedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o createimagedialog.o createimagedialog.cpp

diskeditdialog.o: diskeditdialog.cpp diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		ui_diskeditdialog.h \
		aspeqtsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diskeditdialog.o diskeditdialog.cpp

autoboot.o: autoboot.cpp autoboot.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aspeqtsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o autoboot.o autoboot.cpp

autobootdialog.o: autobootdialog.cpp autobootdialog.h \
		ui_autobootdialog.h \
		mainwindow.h \
		optionsdialog.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aboutdialog.h \
		createimagedialog.h \
		diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		miscutils.h \
		textprinterwindow.h \
		docdisplaywindow.h \
		network.h \
		drivewidget.h \
		infowidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o autobootdialog.o autobootdialog.cpp

atarifilesystem.o: atarifilesystem.cpp atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		diskeditdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o atarifilesystem.o atarifilesystem.cpp

miscutils.o: miscutils.cpp miscutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o miscutils.o miscutils.cpp

textprinterwindow.o: textprinterwindow.cpp textprinterwindow.h \
		ui_textprinterwindow.h \
		aspeqtsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o textprinterwindow.o textprinterwindow.cpp

cassettedialog.o: cassettedialog.cpp cassettedialog.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		ui_cassettedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cassettedialog.o cassettedialog.cpp

docdisplaywindow.o: docdisplaywindow.cpp docdisplaywindow.h \
		ui_docdisplaywindow.h \
		aspeqtsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o docdisplaywindow.o docdisplaywindow.cpp

bootoptionsdialog.o: bootoptionsdialog.cpp bootoptionsdialog.h \
		ui_bootoptionsdialog.h \
		mainwindow.h \
		optionsdialog.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aboutdialog.h \
		createimagedialog.h \
		diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		miscutils.h \
		textprinterwindow.h \
		docdisplaywindow.h \
		network.h \
		drivewidget.h \
		infowidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bootoptionsdialog.o bootoptionsdialog.cpp

network.o: network.cpp network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o network.o network.cpp

logdisplaydialog.o: logdisplaydialog.cpp logdisplaydialog.h \
		ui_logdisplaydialog.h \
		mainwindow.h \
		optionsdialog.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aboutdialog.h \
		createimagedialog.h \
		diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		miscutils.h \
		textprinterwindow.h \
		docdisplaywindow.h \
		network.h \
		drivewidget.h \
		infowidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logdisplaydialog.o logdisplaydialog.cpp

drivewidget.o: drivewidget.cpp drivewidget.h \
		ui_drivewidget.h \
		diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drivewidget.o drivewidget.cpp

pclink.o: pclink.cpp aspeqtsettings.h \
		pclink.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pclink.o pclink.cpp

infowidget.o: infowidget.cpp infowidget.h \
		ui_infowidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o infowidget.o infowidget.cpp

aspeqtsettings.o: aspeqtsettings.cpp aspeqtsettings.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		mainwindow.h \
		optionsdialog.h \
		aboutdialog.h \
		createimagedialog.h \
		diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		miscutils.h \
		textprinterwindow.h \
		docdisplaywindow.h \
		network.h \
		drivewidget.h \
		infowidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aspeqtsettings.o aspeqtsettings.cpp

serialport-unix.o: serialport-unix.cpp serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		sioworker.h \
		headers/atarisio.h \
		aspeqtsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialport-unix.o serialport-unix.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

qrc_i18n.o: qrc_i18n.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_i18n.o qrc_i18n.cpp

qrc_documentation.o: qrc_documentation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_documentation.o qrc_documentation.cpp

qrc_atarifiles.o: qrc_atarifiles.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_atarifiles.o qrc_atarifiles.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_serialport.o: moc_serialport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serialport.o moc_serialport.cpp

moc_sioworker.o: moc_sioworker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sioworker.o moc_sioworker.cpp

moc_optionsdialog.o: moc_optionsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_optionsdialog.o moc_optionsdialog.cpp

moc_aboutdialog.o: moc_aboutdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aboutdialog.o moc_aboutdialog.cpp

moc_diskimage.o: moc_diskimage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_diskimage.o moc_diskimage.cpp

moc_diskimagepro.o: moc_diskimagepro.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_diskimagepro.o moc_diskimagepro.cpp

moc_folderimage.o: moc_folderimage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_folderimage.o moc_folderimage.cpp

moc_miscdevices.o: moc_miscdevices.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_miscdevices.o moc_miscdevices.cpp

moc_createimagedialog.o: moc_createimagedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_createimagedialog.o moc_createimagedialog.cpp

moc_diskeditdialog.o: moc_diskeditdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_diskeditdialog.o moc_diskeditdialog.cpp

moc_autoboot.o: moc_autoboot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_autoboot.o moc_autoboot.cpp

moc_autobootdialog.o: moc_autobootdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_autobootdialog.o moc_autobootdialog.cpp

moc_atarifilesystem.o: moc_atarifilesystem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_atarifilesystem.o moc_atarifilesystem.cpp

moc_miscutils.o: moc_miscutils.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_miscutils.o moc_miscutils.cpp

moc_textprinterwindow.o: moc_textprinterwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_textprinterwindow.o moc_textprinterwindow.cpp

moc_cassettedialog.o: moc_cassettedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cassettedialog.o moc_cassettedialog.cpp

moc_docdisplaywindow.o: moc_docdisplaywindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_docdisplaywindow.o moc_docdisplaywindow.cpp

moc_bootoptionsdialog.o: moc_bootoptionsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bootoptionsdialog.o moc_bootoptionsdialog.cpp

moc_network.o: moc_network.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_network.o moc_network.cpp

moc_logdisplaydialog.o: moc_logdisplaydialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_logdisplaydialog.o moc_logdisplaydialog.cpp

moc_drivewidget.o: moc_drivewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_drivewidget.o moc_drivewidget.cpp

moc_pclink.o: moc_pclink.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pclink.o moc_pclink.cpp

moc_infowidget.o: moc_infowidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_infowidget.o moc_infowidget.cpp

moc_serialport-unix.o: moc_serialport-unix.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serialport-unix.o moc_serialport-unix.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

